drop database tball;
create database tball;
use tball;

CREATE TABLE TEAM (
     ID INT (11) NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , UNIQUE UQ_TEAM_1 (NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE COACH_WIP (
    ID INT (11) NOT NULL AUTO_INCREMENT
    , TEAM_ID INT (11) NOT NULL
    , EMAIL VARCHAR(100) NOT NULL
    , COACH_KEY VARCHAR(100) NOT NULL
    , REGISTERED TINYINT(1) NOT NULL DEFAULT 0
    , PRIMARY KEY (ID)
    , UNIQUE UQ_COACH_WIP_1 (EMAIL, COACH_KEY)
    , CONSTRAINT FK_COACH_WIP_1 FOREIGN KEY (TEAM_ID)
      REFERENCES TEAM (ID)
);

CREATE TABLE COACH (
     ID INT (11) NOT NULL AUTO_INCREMENT
     , TEAM_ID INT (11) NOT NULL
     , FIRST_NAME VARCHAR(100) NOT NULL
     , LAST_NAME VARCHAR(100) NOT NULL
     , USER_NAME VARCHAR(100) NOT NULL
     , EMAIL VARCHAR(100) NOT NULL
     , PWD VARCHAR(100) NOT NULL
     , ADMIN TINYINT(1) NOT NULL DEFAULT 0
     , PRIMARY KEY (ID)
     , UNIQUE UQ_COACH_1 (USER_NAME, EMAIL)
     , CONSTRAINT FK_COACH_1 FOREIGN KEY (TEAM_ID)
       REFERENCES TEAM (ID)
);

CREATE TABLE PLAYER (
     ID INT (11) NOT NULL AUTO_INCREMENT
     , TEAM_ID INT (11) NOT NULL
     , FIRST_NAME VARCHAR(100) NOT NULL
     , LAST_NAME VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_PLAYER_1 FOREIGN KEY (TEAM_ID)
       REFERENCES TEAM (ID)
);

CREATE TABLE POSITION (
	ID INT (11) NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(100) NOT NULL
    , DEFAULT_POSITION TINYINT(1) NOT NULL DEFAULT 0
	, PRIMARY KEY (ID)
);

CREATE TABLE PLAYER_POSITION (
	PLAYER_ID INT (11) NOT NULL
	, POSITION_ID INT (11) NOT NULL
	, UNIQUE UQ_PLAYER_POSITION_1 (PLAYER_ID, POSITION_ID)
	, CONSTRAINT FK_PLAYER_POSITION_1 FOREIGN KEY (PLAYER_ID)
      REFERENCES PLAYER (ID)
	, CONSTRAINT FK_PLAYER_POSITION_2 FOREIGN KEY (POSITION_ID)
      REFERENCES POSITION (ID)
);
